let friendsPageUser=null;
let socialTargetUserId=null;
let socialTargetProfile=null;
let activeSocialTab="following";
const friendsEscape=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const friendAvatar=(id)=>profileAvatarPath(Number(id)||1);
const socialProfileHref=(id)=>`friend.html?user=${encodeURIComponent(id)}`;
function socialIsOwn(){return !socialTargetUserId||socialTargetUserId===friendsPageUser?.id}
function socialSetUrl(tab){const url=new URL(location.href);url.searchParams.set("tab",tab);if(socialIsOwn())url.searchParams.delete("user");else url.searchParams.set("user",socialTargetUserId);history.replaceState({},"",url)}
function socialEmpty(message){document.getElementById("socialList").innerHTML=`<div class="empty-state">${friendsEscape(message)}</div>`}
async function loadTargetProfile(){if(socialIsOwn())return null;const {data,error}=await supabaseClient.rpc("get_public_user_profile",{p_user_id:socialTargetUserId});if(error)throw error;if(!data?.length)throw new Error("This profile could not be found.");return data[0]}
async function loadOwnCounts(){const [requests,following,followers]=await Promise.all([supabaseClient.rpc("get_incoming_follow_requests"),supabaseClient.rpc("get_user_following",{p_user_id:friendsPageUser.id}),supabaseClient.rpc("get_user_followers",{p_user_id:friendsPageUser.id})]);if(requests.error)throw requests.error;if(following.error)throw following.error;if(followers.error)throw followers.error;document.getElementById("friendCount").textContent=(following.data||[]).length;document.getElementById("followerCount").textContent=(followers.data||[]).length;document.getElementById("requestCount").textContent=(requests.data||[]).length;return {requests:requests.data||[],following:following.data||[],followers:followers.data||[]}}
async function loadTargetCounts(){const [following,followers]=await Promise.all([supabaseClient.rpc("get_user_following",{p_user_id:socialTargetUserId}),supabaseClient.rpc("get_user_followers",{p_user_id:socialTargetUserId})]);if(following.error)throw following.error;if(followers.error)throw followers.error;document.getElementById("friendCount").textContent=(following.data||[]).length;document.getElementById("followerCount").textContent=(followers.data||[]).length;return {requests:[],following:following.data||[],followers:followers.data||[]}}
function renderRequests(rows){const root=document.getElementById("socialList");root.innerHTML=rows.length?rows.map(r=>`<article class="request-card"><img class="friend-avatar" src="${friendAvatar(r.avatar_id)}" alt=""><div><h3 class="friend-name">${friendsEscape(r.username||"Anime Fan")}</h3><div class="friend-subtext">Wants to follow you</div></div><div class="request-actions"><a class="friend-action-btn" href="${socialProfileHref(r.follower_user_id)}">View Profile</a><button class="friend-action-btn accept" data-response="accept" data-id="${r.follow_id}">Accept</button><button class="friend-action-btn danger" data-response="decline" data-id="${r.follow_id}">Decline</button></div></article>`).join(""):'<div class="empty-state">No incoming follow requests.</div>';root.querySelectorAll("[data-response]").forEach(b=>b.onclick=async()=>{b.disabled=true;const {error}=await supabaseClient.rpc("respond_to_follow_request",{p_follow_id:Number(b.dataset.id),p_accept:b.dataset.response==="accept"});if(error){alert(error.message);b.disabled=false;return}await refreshSocialPage()})}
function socialActionHtml(row){if(row.listed_user_id===friendsPageUser.id)return '<span class="friend-subtext">You</span>';const status=String(row.viewer_follow_status||"");if(status==="accepted")return `<button class="friend-action-btn danger" data-unfollow="${row.listed_user_id}">Unfollow</button>`;if(status==="pending")return '<button class="friend-action-btn" disabled>Requested</button>';return `<button class="friend-action-btn accept" data-follow="${row.listed_user_id}">Follow</button>`}
function renderUsers(rows,emptyText){const root=document.getElementById("socialList");root.innerHTML=rows.length?rows.map(r=>`<article class="friend-list-card"><img class="friend-avatar" src="${friendAvatar(r.avatar_id)}" alt=""><div><h3 class="friend-name">${friendsEscape(r.username||"Anime Fan")}</h3><div class="friend-subtext">${r.is_private?"Private profile":"Public profile"} • ${Math.round(Number(r.recommendation_points)||0).toLocaleString()} RP</div></div><div class="friend-actions"><a class="friend-action-btn" href="${socialProfileHref(r.listed_user_id)}">View Profile</a>${socialActionHtml(r)}</div></article>`).join(""):`<div class="empty-state">${friendsEscape(emptyText)}</div>`;root.querySelectorAll("[data-unfollow]").forEach(b=>b.onclick=async()=>{if(!confirm("Unfollow this user?"))return;b.disabled=true;const {error}=await supabaseClient.rpc("unfollow_user",{p_user_id:b.dataset.unfollow});if(error){alert(error.message);b.disabled=false;return}await refreshSocialPage()});root.querySelectorAll("[data-follow]").forEach(b=>b.onclick=async()=>{b.disabled=true;const {data,error}=await supabaseClient.rpc("follow_user",{p_user_id:b.dataset.follow});if(error){alert(error.message);b.disabled=false;return}if(data==="pending")alert("Follow request sent.");await refreshSocialPage()})}
function updateSocialHeadings(){const own=socialIsOwn(),name=own?"Your":`${socialTargetProfile?.username||"User"}'s`;document.getElementById("socialPageTitle").innerHTML=`${friendsEscape(name)} <span>${activeSocialTab[0].toUpperCase()+activeSocialTab.slice(1)}</span>`;document.getElementById("socialPageSubtitle").textContent=own?"Manage the people you follow, your followers, and private-profile requests.":`View ${socialTargetProfile?.username||"this user"}'s public social connections.`;document.getElementById("ownSocialActions").hidden=!own;document.getElementById("ownSocialTools").hidden=!own||activeSocialTab!=="following";document.getElementById("requestsTab").hidden=!own;document.querySelectorAll("[data-social-tab]").forEach(b=>b.classList.toggle("active",b.dataset.socialTab===activeSocialTab));const title=activeSocialTab[0].toUpperCase()+activeSocialTab.slice(1);document.getElementById("socialListTitle").textContent=title;document.getElementById("socialListSubtitle").textContent=activeSocialTab==="requests"?"Approve or decline requests to follow your private profile.":activeSocialTab==="followers"?`People following ${own?"you":socialTargetProfile?.username||"this user"}.`:`People ${own?"you follow":`${socialTargetProfile?.username||"this user"} follows`}.`}
async function refreshSocialPage(){document.getElementById("socialList").innerHTML='<div class="loading">Loading users…</div>';try{const data=socialIsOwn()?await loadOwnCounts():await loadTargetCounts();updateSocialHeadings();if(activeSocialTab==="requests")renderRequests(data.requests);else if(activeSocialTab==="followers")renderUsers(data.followers,"No followers yet.");else renderUsers(data.following,"Not following anyone yet.")}catch(e){console.error(e);updateSocialHeadings();const privateMessage=String(e.message||"").toLowerCase().includes("private")?"This user’s followers and following lists are private.":"Could not load this social list.";socialEmpty(privateMessage)}}
async function sendFriendRequest(e){e.preventDefault();const input=document.getElementById("friendCodeInput"),msg=document.getElementById("addFriendMessage");msg.textContent="Following…";const {data,error}=await supabaseClient.rpc("follow_user_by_code",{p_user_code:input.value.trim().toUpperCase()});if(error){msg.textContent=error.message;msg.className="friends-message error";return}input.value="";msg.textContent=data?.status==="accepted"?"You are now following this user.":"Follow request sent.";msg.className="friends-message success";await refreshSocialPage()}
async function loadOwnFriendCode(user){const {data,error}=await supabaseClient.from("profiles").select("friend_code").eq("user_id",user.id).maybeSingle();const el=document.getElementById("yourFriendCode"),btn=document.getElementById("copyFriendCodeBtn"),msg=document.getElementById("copyFriendCodeMessage");if(error){el.textContent="Unavailable";btn.disabled=true;return}const code=String(data?.friend_code||"").toUpperCase();el.textContent=code||"Not generated";btn.onclick=async()=>{await navigator.clipboard.writeText(code);msg.textContent="Code copied."}}
function setupInvite(){const modal=document.getElementById("inviteFriendsModal"),input=document.getElementById("inviteSignupLink"),msg=document.getElementById("inviteFriendsMessage");document.getElementById("inviteFriendsBtn").onclick=()=>{input.value=`${location.origin}${location.pathname.replace(/friends\.html$/,'')}signup.html?ref=${encodeURIComponent(document.getElementById("yourFriendCode").textContent)}`;modal.hidden=false};document.getElementById("closeInviteFriendsBtn").onclick=()=>modal.hidden=true;document.getElementById("copyInviteLinkBtn").onclick=async()=>{await navigator.clipboard.writeText(input.value);msg.textContent="Invite link copied."}}
async function initFriendsPage(user){friendsPageUser=user;const params=new URLSearchParams(location.search);socialTargetUserId=params.get("user");activeSocialTab=["following","followers","requests"].includes(params.get("tab"))?params.get("tab"):"following";if(!socialIsOwn()&&activeSocialTab==="requests")activeSocialTab="following";document.querySelectorAll("[data-social-tab]").forEach(b=>b.onclick=()=>{activeSocialTab=b.dataset.socialTab;socialSetUrl(activeSocialTab);refreshSocialPage()});document.getElementById("addFriendForm").addEventListener("submit",sendFriendRequest);await loadOwnFriendCode(user);setupInvite();try{socialTargetProfile=await loadTargetProfile();await refreshSocialPage()}catch(e){console.error(e);socialEmpty("Could not load this profile.")}}
