let ratingsRecords=[],ratingsFranchises=[],ratingsTab="rated";
function rEsc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function recordRating(r){return matEntryRating(r)}
async function load(){const [a,f]=await Promise.all([supabaseClient.from("anime").select("*").order("title"),matLoadOwnFranchises()]);if(a.error)throw a.error;ratingsRecords=a.data||[];ratingsFranchises=f}
function buildItems(){const grouped=new Set(ratingsRecords.filter(x=>x.franchise_key).map(x=>Number(x.franchise_key)));const fs=ratingsFranchises.map(f=>{let rating=matFranchiseRating(f);if(rating===null){const scores=ratingsRecords.filter(x=>Number(x.franchise_key)===Number(f.franchise_key)).map(recordRating).filter(Number.isFinite);rating=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:null}return{kind:"franchise",title:f.title,status:f.status,rating,posterId:f.cover_anilist_id,href:`franchise.html?key=${f.franchise_key}`,editHref:`franchise.html?key=${f.franchise_key}#rating`}});const standalone=ratingsRecords.filter(x=>!x.franchise_key).map(x=>({kind:"anime",title:x.title,status:x.status,rating:recordRating(x),posterId:x.anilist_id,href:`anime.html?id=${x.id}`,editHref:`anime.html?id=${x.id}&edit=1`,favorite:x.favorite}));return[...fs,...standalone]}
async function fill(){const elements=[...document.querySelectorAll("[data-rating-poster]")];const ids=elements.map(el=>Number(el.dataset.ratingPoster)).filter(Number.isFinite);let map=new Map();try{const rows=await matFetchMediaBatch(ids);map=new Map(rows.map(row=>[Number(row.id),row]))}catch(error){console.warn("Rating posters could not be refreshed; cached artwork will be used when available.",error)}for(const el of elements){const m=map.get(Number(el.dataset.ratingPoster));if(!m)continue;const url=m?.coverImage?.extraLarge||m?.coverImage?.large||"";const isAdult=Boolean(m?.isAdult);el.classList.toggle("mat-adult-poster-hidden",isAdult&&!matShow18Posters());el.innerHTML=url?`<img src="${rEsc(url)}" alt="Anime poster">${matAdultPosterOverlay(isAdult)}`:"🎌"}}
function render(){const list=document.getElementById("ratingsList"),meta=document.getElementById("ratingsMeta"),controls=document.getElementById("ratedControls");let items=buildItems().filter(x=>String(x.status).toLowerCase()==="completed");if(ratingsTab==="unrated"){controls.classList.add("hidden");items=items.filter(x=>x.rating===null);meta.textContent=`${items.length} completed ${items.length===1?"item needs":"items need"} a rating`}else{controls.classList.remove("hidden");items=items.filter(x=>x.rating!==null);const s=document.getElementById("ratingsSearch").value.toLowerCase(),sort=document.getElementById("ratingsSort").value,fav=document.getElementById("favoritesOnly").checked;if(s)items=items.filter(x=>x.title.toLowerCase().includes(s));if(fav)items=items.filter(x=>x.favorite);items.sort((a,b)=>sort==="lowest"?a.rating-b.rating:sort==="az"?a.title.localeCompare(b.title):sort==="za"?b.title.localeCompare(a.title):b.rating-a.rating);meta.textContent=`${items.length} rated ${items.length===1?"item":"items"} shown`}
 list.innerHTML=items.length?items.map(x=>`<article class="rating-row rated-rating-row"><a class="rating-row-main" href="${x.href}"><div class="rating-poster-placeholder" data-rating-poster="${x.posterId}">🎌</div><div><h2 class="rating-row-title">${rEsc(x.title)}${x.kind==="franchise"?' <span class="rating-franchise-label">Franchise</span>':""}</h2><div class="rating-breakdown">Completed • ${x.rating===null?"Rating incomplete":x.kind==="franchise"?"Franchise rating":"Anime rating"}</div></div>${x.rating===null?"":`<div class="rating-overall">⭐ ${x.rating.toFixed(1)}</div>`}</a><a class="rate-now-btn" href="${x.editHref}">${x.rating===null?"Rate":"Edit Rating"}</a></article>`).join(""):'<div class="empty-state">Nothing in this section.</div>';fill()}
async function initRatings(){try{await load();document.querySelectorAll(".ratings-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".ratings-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");ratingsTab=b.dataset.tab;render()});["ratingsSearch","ratingsSort","favoritesOnly"].forEach(id=>document.getElementById(id).addEventListener(id==="ratingsSearch"?"input":"change",render));render()}catch(e){document.getElementById("ratingsList").innerHTML=`<div class="error">${rEsc(e.message)}</div>`}}
